EOF = 'EOF'

INTEGER = 'INTEGER'
INTEGER_CONST = 'INTEGER_CONST'
REAL = 'REAL'
REAL_CONST = 'REAL_CONST'

LPAREN, RPAREN, = ('(', ')',)
PLUS, MINUS = ('PLUS', 'MINUS')
MUL, FLOAT_DIV, INTEGER_DIV = ('MUL', 'FLOAT_DIV', 'INTEGER_DIV')

ID = 'ID'
ASSIGN = 'ASSIGN'
SEMI, COLON, DOT, COMMA,  = ('SEMI', 'COLON', 'DOT', 'COMMA')

BEGIN, END = ('BEGIN', 'END')
PROGRAM = 'PROGRAM'
VAR = 'VAR'